config:
  BinderHub:
    use_registry: true
    image_prefix: xxx/dl-
    #jupyterhub url
    hub_url: https://xx.xx.com
    https:
      #binderhub url
      hosts:
        - xxx.xxx.com
      letsencrypt:
        contactEmail: xxx@gmail.com
